# References:
#   - https://tox.wiki/en/latest/
#   - https://github.com/tox-dev/tox-uv
# TODO(amir): add `3.12` once glmnet adds the wheel.
# https://github.com/replicahq/python-glmnet/issues/5

[tox]
requires =
    tox>=4.22
    tox-uv>=1.25
envlist = py{39,310,311}
skip_missing_interpreters = True

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    dev
    docs
uv_python_preference = only-managed
allowlist_externals =
    uv
    poe
commands =
    poe check
    poe test
    poe sphinx
    poe build
