name: Documentation Improvements
description: Improve documentation ...
title: "[DOCUMENTATION]: "
labels: ["documentation"]
assignees:
  - amirhessam88
  - Tsmith5151
  - eitanlees
  - mkohram
  - b-mohebali
  - nicholasjma
body:
  - type: markdown
    attributes:
      value: |
        The SlickML🧞 core team appreciate your time to fill out this documentation improvement ...

  - type: input
    id: contact
    attributes:
      label: Contact Details [Optional]
      description: How can we get in touch with you if we need more info?
      placeholder: your-email@example.com
    validations:
      required: false

  - type: textarea
    id: documentation-improvement
    attributes:
      label: Describe the documentation improvements you are interested in ...
      description: A clear and concise description of what you would like to be improved ...
      placeholder: "The improvements that can be added to SlickML🧞 can be ..."
    validations:
      required: true

  - type: textarea
    id: improvement-solution
    attributes:
      label: Any other comments?
      description: Add any other context about the improvements here ...
      placeholder: "This is (also) related to issue #42."
    validations:
      required: false
