####################################################################################################
# Continuous Integration [Lint, Test, Build] on All Pull-Requests + Push to Master
####################################################################################################
# References:
# - https://docs.astral.sh/uv/guides/integration/github/
# - https://github.com/astral-sh/setup-uv
# - https://github.com/codecov/codecov-action
# Adapted from: https://github.com/slickml/slick-tune/blob/master/.github/workflows/ci.yml
####################################################################################################
name: build

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  ci:
    #----------------------------------------------
    # -----  setup operating system (os)  -----
    #----------------------------------------------
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # TODO(amir): enable `windows-latest` and fix possible glmnet issues
        # TODO(amir): add `"3.12"` once the glmnet wheel is released
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      #----------------------------------------------
      # ----- check-out repo and set-up python -----
      #----------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      # -----  install & configure uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - name: Install Dependencies
        run: uv sync --locked --all-extras --all-groups

      - name: Install Poe the Poet
        run: uv tool install poethepoet

      #----------------------------------------------
      #  -----  Integration test suite  -----
      #----------------------------------------------
      - name: Lint
        run: poe check

      - name: Test
        run: |
          poe greet
          poe test

      - name: Build
        run: |
          poe greet
          poe build

      #----------------------------------------------
      #  ---  Upload test coverage to Codecov  ---
      #----------------------------------------------
      - name: Codecov
        # NOTE: only run code coverage with one Python Version and OS; the rest is not needed
        if: ${{ matrix.python-version == '3.9' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./xmlcov/
          fail_ci_if_error: true
          files: ./xmlcov/coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
