####################################################################################################
# Continuous Integration [Lint, Test, Build] on All Pull-Requests + Push to Master
####################################################################################################
# References:
# - https://github.com/snok/install-poetry
# - https://github.com/actions/setup-python#caching-packages-dependencies
# - https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions
# - https://github.com/codecov/codecov-action
####################################################################################################
name: build

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  ci:
    #----------------------------------------------
    # -----  setup operating system (os)  -----
    #----------------------------------------------
    runs-on: ${{ matrix.os }}
    strategy:
      # TODO(amir): currently this is `false` so we can use the `poetry-cache` of `python v3.8`
      # once the stupid `glmnet` dependency is resolved, change `fail-fast = True`
      fail-fast: false
      matrix:
        # TODO(amir): enable `windows-latest`, `macos-latest` and fix possible `poetry` issues and glmnet
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      #----------------------------------------------
      # ----- check-out repo and set-up python -----
      #----------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      # -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #  -----  load cached dependencies  -----
      #----------------------------------------------
      - name: Load Cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          # TODO(amir): here, we explicitly set the key independent of what `python-version` we are running
          # the main issue is with `glmnet` that does not currently support `python v3.9 and 3.10`
          # therefore, all the CI jobs for those python versions failed at first, then we re-run the
          # jobs, the cached venv using `python v3.8` will be retrieved and the jobs will run successfully
          # ideally, we should be able to add `python-versions` here to distinguish between caches
          # key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          # NOTE: `glmnet` has not been updated since 2020; trying to build it on-the-fly
          # https://github.com/civisanalytics/python-glmnet/issues/79
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - name: Install Dependencies
        run: poetry install -vv
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      #----------------------------------------------
      #  -----  Integration test suite  -----
      #----------------------------------------------
      # TODO(amir): de-dup the `source .venv/bin/activate` (`source $VENV`) command
      - name: Lint
        run: |
          source $VENV
          poe check
      - name: Test
        run: |
          source $VENV
          poe greet
          poe test
      - name: Build
        run: |
          source $VENV
          poe greet
          poetry build
      #----------------------------------------------
      #  ---  Upload test coverage to Codecov  ---
      #----------------------------------------------
      - name: Codecov
        # NOTE: only run code coverage with one Python Version and OS; the rest is not needed
        if: ${{ matrix.python-version == '3.9' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./xmlcov/
          fail_ci_if_error: true
          files: ./xmlcov/coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
