####################################################################################################
# Continuous Deployment [GitHub Metrics] Daily and on Push to Master
####################################################################################################
# References:
# - https://github.com/lowlighter/metrics#-documentation
# - https://github.com/lowlighter/metrics
####################################################################################################
name: metrics
on:
  # Schedule updates daily at 00:00 AM
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push:
    branches: ["master"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          #----------------------------------------------
          # ----- Metrics Options -----
          #----------------------------------------------
          user: slickml
          template: classic
          base: ""
          config_timezone: America/Chicago
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
